version: '4'
services:
  userapp:
    build:
      context: ./UserFront # Ruta a la carpeta que contiene el Dockerfile
    ports:
      - "7010:80" # Mapeo del puerto del contenedor a tu máquina

  adminapp:
    build: 
      context: ./AdminFront
    ports:
      - "9090:80"